// Mesmos ícones Lucide do protótipo (classes `icon-*`), por nome. Cresce a cada tela.
import {
  Activity,
  ArrowUp,
  Box,
  Brain,
  CalendarClock,
  ChevronDown,
  ChevronUp,
  Circle,
  CircleCheck,
  Copy,
  CreditCard,
  Drama,
  FileSpreadsheet,
  FileText,
  GitFork,
  GitPullRequest,
  Globe,
  History,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  LoaderCircle,
  MessageCircle,
  MessageSquare,
  Mic,
  Moon,
  OctagonPause,
  PanelRight,
  Paperclip,
  Phone,
  Play,
  Plus,
  Radar,
  RadioTower,
  Receipt,
  RotateCcw,
  RotateCw,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Settings2,
  ShieldCheck,
  Sparkles,
  Square,
  SquareTerminal,
  Sun,
  Undo2,
  Users,
  Workflow,
  Mail,
  PartyPopper,
  Pause,
  AtSign,
  BellRing,
  BookOpenText,
  Bug,
  CircleHelp,
  Flag,
  GitBranch,
  Hourglass,
  PenLine,
  SquareKanban,
  WandSparkles,
  X,
  Zap,
  AppWindow,
  ArrowRight,
  AudioLines,
  CalendarPlus,
  Check,
  Eye,
  Hash,
  Image,
  Pencil,
  Pin,
  Plug,
  Rocket,
  Trash2,
  UserRound,
  Wrench,
  ArrowRightLeft,
  Briefcase,
  Building2,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CirclePause,
  CloudOff,
  CodeXml,
  Croissant,
  Ellipsis,
  Folder,
  Glasses,
  HeartPulse,
  Info,
  KeyRound,
  Layers,
  Lock,
  MessagesSquare,
  Star,
  Store,
  TriangleAlert,
  Unplug,
  User,
  Clock,
  Ear,
  Link2,
  Minus,
  Unlink,
  ArrowLeft,
  Ban,
  Braces,
  Container,
  Database,
  Hand,
  List,
  Server,
  ShieldAlert,
  Timer,
  TimerOff,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-up": ArrowUp,
  box: Box,
  brain: Brain,
  "calendar-clock": CalendarClock,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-check": CircleCheck,
  copy: Copy,
  "credit-card": CreditCard,
  drama: Drama,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "git-fork": GitFork,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  history: History,
  inbox: Inbox,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "loader-circle": LoaderCircle,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  moon: Moon,
  "octagon-pause": OctagonPause,
  "panel-right": PanelRight,
  paperclip: Paperclip,
  phone: Phone,
  play: Play,
  plus: Plus,
  radar: Radar,
  "radio-tower": RadioTower,
  receipt: Receipt,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "scan-search": ScanSearch,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  square: Square,
  "square-terminal": SquareTerminal,
  sun: Sun,
  "undo-2": Undo2,
  users: Users,
  workflow: Workflow,
  wrench: Wrench,
  "user-round": UserRound,
  "trash-2": Trash2,
  rocket: Rocket,
  plug: Plug,
  pin: Pin,
  pencil: Pencil,
  image: Image,
  hash: Hash,
  eye: Eye,
  check: Check,
  "calendar-plus": CalendarPlus,
  "audio-lines": AudioLines,
  "arrow-right": ArrowRight,
  "app-window": AppWindow,
  zap: Zap,
  x: X,
  "wand-sparkles": WandSparkles,
  "square-kanban": SquareKanban,
  "pen-line": PenLine,
  hourglass: Hourglass,
  "git-branch": GitBranch,
  flag: Flag,
  "circle-help": CircleHelp,
  bug: Bug,
  "book-open-text": BookOpenText,
  "bell-ring": BellRing,
  "at-sign": AtSign,
  pause: Pause,
  "party-popper": PartyPopper,
  mail: Mail,
  "arrow-right-left": ArrowRightLeft,
  "briefcase": Briefcase,
  "building-2": Building2,
  "chevron-right": ChevronRight,
  "chevrons-up-down": ChevronsUpDown,
  "circle-alert": CircleAlert,
  "circle-pause": CirclePause,
  "cloud-off": CloudOff,
  "code-xml": CodeXml,
  "croissant": Croissant,
  "ellipsis": Ellipsis,
  "folder": Folder,
  "glasses": Glasses,
  "heart-pulse": HeartPulse,
  "info": Info,
  "key-round": KeyRound,
  "layers": Layers,
  "lock": Lock,
  "messages-square": MessagesSquare,
  "star": Star,
  "store": Store,
  "triangle-alert": TriangleAlert,
  "unplug": Unplug,
  "user": User,
  clock: Clock,
  ear: Ear,
  "link-2": Link2,
  minus: Minus,
  unlink: Unlink,
  "arrow-left": ArrowLeft,
  ban: Ban,
  braces: Braces,
  container: Container,
  database: Database,
  hand: Hand,
  list: List,
  server: Server,
  "shield-alert": ShieldAlert,
  timer: Timer,
  "timer-off": TimerOff,
};

export function Icon({ name, size = 16, color, className }: { name: string; size?: number; color?: string; className?: string }) {
  const C = ICONS[name] ?? Sparkles;
  return <C size={size} color={color} className={className} aria-hidden="true" style={{ flex: "none" }} />;
}
