// Mesmos ícones Lucide do protótipo (classes `icon-*`), por nome. Cresce a cada tela.
import {
  Activity,
  ArrowUp,
  Box,
  Brain,
  CalendarClock,
  ChevronDown,
  ChevronUp,
  Circle,
  CircleCheck,
  Copy,
  CreditCard,
  Drama,
  FileSpreadsheet,
  FileText,
  GitFork,
  GitPullRequest,
  Globe,
  History,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  LoaderCircle,
  MessageCircle,
  MessageSquare,
  Mic,
  Moon,
  OctagonPause,
  PanelRight,
  Paperclip,
  Phone,
  Play,
  Plus,
  Radar,
  RadioTower,
  Receipt,
  RotateCcw,
  RotateCw,
  ScrollText,
  Search,
  Send,
  Settings2,
  ShieldCheck,
  Sparkles,
  Square,
  SquareTerminal,
  Sun,
  Undo2,
  Users,
  Workflow,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-up": ArrowUp,
  box: Box,
  brain: Brain,
  "calendar-clock": CalendarClock,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-check": CircleCheck,
  copy: Copy,
  "credit-card": CreditCard,
  drama: Drama,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "git-fork": GitFork,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  history: History,
  inbox: Inbox,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "loader-circle": LoaderCircle,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  moon: Moon,
  "octagon-pause": OctagonPause,
  "panel-right": PanelRight,
  paperclip: Paperclip,
  phone: Phone,
  play: Play,
  plus: Plus,
  radar: Radar,
  "radio-tower": RadioTower,
  receipt: Receipt,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  square: Square,
  "square-terminal": SquareTerminal,
  sun: Sun,
  "undo-2": Undo2,
  users: Users,
  workflow: Workflow,
};

export function Icon({ name, size = 16, color, className }: { name: string; size?: number; color?: string; className?: string }) {
  const C = ICONS[name] ?? Sparkles;
  return <C size={size} color={color} className={className} aria-hidden="true" style={{ flex: "none" }} />;
}
